### ISSUE TITLE
register_localizations: error arising from comparison between nans?

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#143]
I get this error when running register_localizations:
```
Plotting barcode localization map for ROI: 1
Traceback (most recent call last):
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 150, in <module>
    main()
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 116, in main
    fc.register_localizations(current_param, label)
  File "/home/marcnol/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 352, in register_localizations
    register_localizations_instance.register()
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/register_localizations.py", line 475, in register
    self.register_barcode_map_file(file)
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/register_localizations.py", line 416, in register_barcode_map_file
    table.compares_localizations(
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/localization_table.py", line 271, in compares_localizations
    if np.isnan(diff):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()```

**Comment by marcnol** [comment]
This is arising when localization tables have exact duplicate spots. For the moment I am using a.any() as a condition to  avoid this problem but we should look at why there are duplicate localizations, see Issue 144

**Comment by marcnol** [comment]
This should be fixed if localizations are not repeated
