### ISSUE TITLE
segmentSources3D 'voxel_size_z'

### ISSUE THREAD

**Issue by olivier469110** [marcnol/pyHiM#35]
I'm using refactoringPWDmatrix branch in this folder /mnt/grey/DATA/rawData_2022/Experiment_10_Olivier_HiM_Multiplex_pancreas/Deconvolved/Analysis/019_ROI_Links

I have executed pyHiM -F . 
All the following section were processed :  
['makeProjections', 'appliesRegistrations', 'alignImages', 'alignImages3D', 'segmentMasks', 'segmentMasks3D', 'segmentSources3D', 'buildHiMmatrix']

In segmentSources3D 

>>>Processing roi:[019] cycle:[RT27]<<<
$ File:scan_002_RT27_019_ROI_converted_decon_ch01.tif
$ Reduced Z-planes from 70 to 35
> Reducing 3D image size by slicing around focal plane
100%|███████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.90it/s]
$ Focal plane found: 11, zRange = range(4, 18), imageSize = (14, 2048, 2048)
> Applying existing XY shift...
$ Applies shift = [14.72 ,-6.40]
> Shifting 14 planes with 1 thread...
$ Done shifting 3D image.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Segmenting 14 planes using 1 worker...
> Loading model stardist_18032021_single_loci from /mnt/grey/DATA/users/marcnol/models/StarDist3D/training3Dbarcodes/models...
2022-02-28 10:02:41.863008: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-02-28 10:02:41.863054: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: darwin
2022-02-28 10:02:41.863061: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: darwin
2022-02-28 10:02:41.863234: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.80.0
2022-02-28 10:02:41.863257: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.80.0
2022-02-28 10:02:41.863262: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.80.0
2022-02-28 10:02:41.863578: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.458824, nms_thresh=0.3.
100%|█████████████████████████████████████████████████████████████████████████████████| 64/64 [01:02<00:00,  1.02it/s]
 > Constructing distance matrix from 3D binary mask...
 > Deblending sources in 3D by watersheding...
$ Number of sources detected by image segmentation: 495
> Refits spots using gaussian 3D fittings...
 > Rescales image values after reinterpolation
Traceback (most recent call last):
  File "/home/messina/pyHiM/src/pyHiM.py", line 82, in <module>
    HiM.segmentSources3D(param, label)
  File "/home/messina/pyHiM/src/fileProcessing/functionCaller.py", line 191, in segmentSources3D
    _segmentSources3D.segmentSources3D()
  File "/home/messina/pyHiM/src/imageProcessing/segmentSources3D.py", line 535, in segmentSources3D
    self.segmentSources3DinFolder()
  File "/home/messina/pyHiM/src/imageProcessing/segmentSources3D.py", line 485, in segmentSources3DinFolder
    outputTables.append(self.segmentSources3D_file(fileName2Process))
  File "/home/messina/pyHiM/src/imageProcessing/segmentSources3D.py", line 379, in segmentSources3D_file
    spots_subpixel = fit_subpixel(image3D_aligned,
TypeError: fit_subpixel() got an unexpected keyword argument 'voxel_size_z

**Comment by marcnol** [comment]
See if commit 56c8d96cc5b44b165a5b4c57489cafba83026b1d in the development branch fixes the issue...
This was because bigfish changed input parameters for fit_subpixel()...

**Comment by olivier469110** [comment]
Seems to be working
