### ISSUE TITLE
ValueError when running segmentSources3D

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#45]
see Traceback (most recent call last):
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 84, in <module>
    HiM.segmentSources3D(param, label)
  File "/home/marcnol/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 191, in segmentSources3D
    _segmentSources3D.segmentSources3D()
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 543, in segmentSources3D
    self.segmentSources3DinFolder()
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 493, in segmentSources3DinFolder
    outputTables.append(self.segmentSources3D_file(fileName2Process))
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 318, in segmentSources3D_file
    focalPlaneMatrix, zRange, _= _reinterpolatesFocalPlane(image3D0,blockSizeXY = p["blockSizeXY"], window=p["zWindow"])
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/imageProcessing.py", line 1375, in _reinterpolatesFocalPlane
    focalPlaneMatrix, fwhm, block= calculatesFocusPerBlock(data, blockSizeXY=blockSizeXY)
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/imageProcessing.py", line 1236, in calculatesFocusPerBlock
    focalPlaneMatrix[i, j], fwhm[i,j] = focalPlane(block[i, j])
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/imageProcessing.py", line 1182, in focalPlane
    fitResult, _= fit1DGaussian_scipy(xCoord,LaplacianVariance,title='laplacian variance z-profile',verbose=verbose)
  File "/home/marcnol/Repositories/pyHiM/src/imageProcessing/imageProcessing.py", line 282, in fit1DGaussian_scipy
    fitgauss = spo.curve_fit(gaussian, x, y)
  File "/home/marcnol/anaconda3/envs/pyHiM/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 734, in curve_fit
    ydata = np.asarray_chkfinite(ydata, float)
  File "/home/marcnol/anaconda3/envs/pyHiM/lib/python3.7/site-packages/numpy/lib/function_base.py", line 486, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by marcnol** [comment]
fix at commit 8dfa9de067e0710840e717efbe523c435a0656e2
