### ISSUE TITLE
build_trace tries to assign localizations outside of the image!

### ISSUE THREAD

**Issue by marcnol** [marcnol/pyHiM#49]
Traceback (most recent call last):
  File "/home/marcnol/Repositories/pyHiM/src/pyHiM.py", line 108, in <module>
    HiM.build_traces(param, label)
  File "/home/marcnol/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 229, in build_traces
    build_traces_instance.run()
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/build_traces.py", line 583, in run
    self.launch_analysis(file)
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/build_traces.py", line 545, in launch_analysis
    self.build_trace_by_masking(barcodeMap)
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/build_traces.py", line 410, in build_trace_by_masking
    self.assign_masks(
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/build_traces.py", line 374, in assign_masks
    self.alignByMasking()
  File "/home/marcnol/Repositories/pyHiM/src/matrixOperations/build_traces.py", line 165, in alignByMasking
    maskID = self.Masks[x_int][y_int]
IndexError: index 2048 is out of bounds for axis 0 with size 2048

**Comment by marcnol** [comment]
issue fixed in 03b8fc867dd4745b298b0f6f7ebc905f6f31a072
