### ISSUE TITLE
Bug when running segmentSources3D

### ISSUE THREAD

**Issue by jbfiche** [marcnol/pyHiM#55]
Data are located here : /mnt/grey/DATA/users/JB/test_HiM/2022_04_09_two_color/AF647_AF750/pyHiM_analysis/AF647_raw/Deconvolved_AF647
branch : development
command : pyHiM.py -C segmentSources3D

PyHiM is launched correctly, it is able to detect the 12 files, 2 ROIs. However, after slicing the stack the following error is observed :  

$ Focal plane found: 15, zRange = range(8, 22), imageSize = (14, 2048, 2048)
Traceback (most recent call last):
  File "/home/jb/Repositories/pyHiM/src/pyHiM.py", line 84, in <module>
    HiM.segmentSources3D(param, label)
  File "/home/jb/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 191, in segmentSources3D
    _segmentSources3D.segmentSources3D()
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 549, in segmentSources3D
    self.segmentSources3DinFolder()
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 499, in segmentSources3DinFolder
    outputTables.append(self.segmentSources3D_file(fileName2Process))
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 352, in segmentSources3D_file
    printLog("$ Applies shift = [{:.2f} ,{:.2f}]".format(shift[0],shift[1]))
UnboundLocalError: local variable 'shift' referenced before assignment

NB : the same result was obtained on my local environment or on Darwin using Olivier's pyHiM39 environment
NB2: the segmentation is working smoothly for the RT corresponding to the "referenceFiducial"

**Comment by marcnol** [comment]
did you run alignImages?

there is an order in which modules need to be run. 

SegmentSources3D will search for a dictionary of drift corrections which it did not find! 

We need to modify the code to produce a more intelligible message.

**Comment by marcnol** [comment]
JB can you test fix in branch:
fix/issue_55

**Comment by jbfiche** [comment]
New error : 

$ Focal plane found: 11, zRange = range(4, 18), imageSize = (14, 2048, 2048)
Traceback (most recent call last):
  File "/home/jb/Repositories/pyHiM/src/pyHiM.py", line 84, in <module>
    HiM.segmentSources3D(param, label)
  File "/home/jb/Repositories/pyHiM/src/fileProcessing/functionCaller.py", line 191, in segmentSources3D
    _segmentSources3D.segmentSources3D()
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 553, in segmentSources3D
    self.segmentSources3DinFolder()
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 503, in segmentSources3DinFolder
    outputTables.append(self.segmentSources3D_file(fileName2Process))
  File "/home/jb/Repositories/pyHiM/src/imageProcessing/segmentSources3D.py", line 350, in segmentSources3D_file
    "ROI:" + self.ROI, label))
AttributeError: 'segmentSources3D' object has no attribute 'ROI'

**Comment by marcnol** [comment]
please provide your working directory and command executed, otherwise very difficult to debug!

**Comment by marcnol** [comment]
fixed this in commit 2c666904cff40b25a130f43b54518d6ad4aaf4c5
can you check it works on your end?

**Comment by marcnol** [comment]
Fixed in commit 2c666904cff40b25a130f43b54518d6ad4aaf4c5
